apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paper-e0-oracle-data
  namespace: cloud-minecraft-paper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 10Gi
